# Generated by Django 5.1 on 2024-08-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('idEmpleado', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleados')),
            ],
            options={
                'verbose_name': 'Facturacion',
                'verbose_name_plural': 'Facturacion',
            },
        ),
    ]
