# Generated by Django 5.1 on 2024-08-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Facturacion', '0001_initial'),
        ('Propiedades', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='idPropiedad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Propiedades.propiedades'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='idPropietario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
    ]
