# Generated by Django 5.1 on 2024-08-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('document', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('user_type', models.CharField(choices=[('PROP', 'Propietario'), ('ARR', 'Arrendatario')], default='ARR', max_length=30, verbose_name='User Type')),
                ('register_date', models.DateField(verbose_name='Date of register')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuario',
            },
        ),
    ]
