# Generated by Django 5.1 on 2024-08-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDePropiedad', models.CharField(max_length=100, verbose_name='Tipo De Propiedad')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('idEmpleado', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleados')),
                ('idPropetario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Propiedades',
                'verbose_name_plural': 'Propiedades',
            },
        ),
    ]
