# Generated by Django 5.1 on 2024-08-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('lastName', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('idEmpleado', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Documento')),
                ('position', models.CharField(choices=[('ASE', 'Asesor'), ('LIM', 'Limpieza'), ('ADM', 'Administrativo')], default='ASE', max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Empleados',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
